#!/usr/bin/env bash
clear
current_path=`pwd`
script_path=`dirname $0`
CA_PATH=$HOME/CA

if [ -z $ISSUING_CA_PATH ]
then
	echo "Path to the Issuing CA not found."
	echo -n "ISSUING CA NAME : "
	read ISSUING_CA_NAME
	ISSUING_CA_PATH=$HOME/CA/$ISSUING_CA_NAME
fi

echo
echo "- This script automates the creation of OpenSSL based Online Certificate Status Protocol (OCSP)."
echo "- You're only required to input some information during setup."
echo "- This script assumes that you've already setup a Root CA."
echo
echo -n "Enter OCSP Server name : "
read OCSP_NAME

CA_PATH=$HOME/CA
OCSP_PATH=$CA_PATH/$OCSP_NAME

mkdir -p $OCSP_PATH/{private,cert,csr}
chmod 700 $OCSP_PATH
chmod 700 $OCSP_PATH/private
echo "directories and files for "$OCSP_NAME" setup successfully.".
echo "---------------------------------------------------------------------"
echo

WEB_URL=`hostname`

cp $script_path/templateocsp $OCSP_PATH
OCSP_CNF=$OCSP_PATH/$OCSP_NAME.cnf
mv $OCSP_PATH/templateocsp $OCSP_CNF

ISSUING_CNF=$ISSUING_CA_PATH/$ISSUING_CA_NAME.cnf

echo "Preparing configuration file for "$OCSP_NAME"."
echo -n "Country (C)		: "
read  OCSP_C
echo -n "State (ST)		: "
read OCSP_ST
echo -n "Location (L)		: "
read OCSP_L
echo -n "Organization (O)	: "
read OCSP_O
echo -n "Org. Unit (OU)		: "
read OCSP_OU

sed -i 's@COMMON_NAME@'"$OCSP_NAME"'@' $OCSP_CNF
sed -i 's@COUNTRY@'"$OCSP_C"'@' $OCSP_CNF
sed -i 's@STATE@'"$OCSP_ST"'@' $OCSP_CNF
sed -i 's@LOCATION@'"$OCSP_L"'@' $OCSP_CNF
sed -i 's@ORGANIZATION@'"$OCSP_O"'@' $OCSP_CNF
sed -i 's@ORG_UNIT@'"$OCSP_OU"'@' $OCSP_CNF

echo "Configuration file for "$OCSP_NAME" ready."
echo "---------------------------------------------------------------------"
echo
echo "Select key type."
echo "(1) for RSA. (default)"
echo "(2) for ECDSA."
echo "(3) for MLDSA."
echo -n "Key Type : "
read KEY_TYPE

if [ -z "$KEY_TYPE" ]
then
	KEY_TYPE=1
fi

if [ $KEY_TYPE -eq 1 ]
then
	echo -n "Key size (default 2048) : "
	read RSA_KEY_SIZE
	if [ -z "$RSA_KEY_SIZE" ] || [ "$RSA_KEY_SIZE" -lt 2048 ]
	then
		RSA_KEY_SIZE=2048
	fi
	openssl genpkey -algorithm rsa -pkeyopt rsa_keygen_bits:$RSA_KEY_SIZE -quiet | openssl pkcs8 -passout file:/etc/machine-id -topk8 -out $OCSP_PATH/private/$OCSP_NAME.key
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	chmod 400 $OCSP_PATH/private/$OCSP_NAME.key
fi

if [ $KEY_TYPE -eq 2 ]
then
	echo -n "ECDSA Curve (default secp384r1) : "
	read EC_CURVE
	if [ -z "$EC_CURVE" ]
	then
		EC_CURVE="secp384r1"
	fi
	openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:$EC_CURVE | openssl pkcs8 -passout file:/etc/machine-id -topk8 -out $OCSP_PATH/private/$OCSP_NAME.key
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	chmod 400 $OCSP_PATH/private/$OCSP_NAME.key
fi

if [ $KEY_TYPE -eq 3 ]
then
	echo "  - MLDSA44 (default)"
	echo "  - MLDSA65"
	echo "  - MLDSA87"
	echo -n "  MLDSA size : "
	read MLDSA_SIZE
	if [ -z "$MLDSA_SIZE" ]
	then
		MLDSA_SIZE="MLDSA44"
	fi
	openssl genpkey -algorithm $MLDSA_SIZE -quiet | openssl pkcs8 -passout file:/etc/machine-id -topk8 -out $OCSP_PATH/private/$OCSP_NAME.key
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	chmod 400 $OCSP_PATH/private/$OCSP_NAME.key
fi

echo "Private key for $OCSP_NAME generated successfully."
echo "---------------------------------------------------------------------"
echo
echo -n "Certificate validity (days, default 1825) : "
read VALIDITY_DAYS

if [ -z "$VALIDITY_DAYS" ]
then
	VALIDITY_DAYS=1825
fi

if [[ -z "${ISSUING_CA_NAME}" ]]
then
	echo -n "Issuing CA name : "
	read ISSUING_CA_NAME
fi
if [[ -z "${ISSUING_CA_PATH}" ]]
then
	echo -n "Issuing CA Path : "
	read ISSUING_CA_PATH
fi

openssl req -config $OCSP_CNF -new -batch -sha256 -key $OCSP_PATH/private/$OCSP_NAME.key -passin file:/etc/machine-id -out $OCSP_PATH/csr/$OCSP_NAME.csr
if [ $? -ne 0 ]
then
	exit 1
fi

openssl ca -config $ISSUING_CNF -batch -passin file:/etc/machine-id -extensions ocsp -days $VALIDITY_DAYS -notext -md sha256 -in $OCSP_PATH/csr/$OCSP_NAME.csr -out $OCSP_PATH/cert/$OCSP_NAME.cer
if [ $? -ne 0 ]
then
        exit 1
fi

chmod 444 $OCSP_PATH/cert/$OCSP_NAME.cer
openssl verify -CAfile $ISSUING_CA_PATH/cert/cacert.cer $OCSP_PATH/cert/$OCSP_NAME.cer
cat $ISSUING_CA_PATH/cert/$ISSUING_CA_NAME.cer $ROOT_CA_PATH/cert/$ROOT_CA_NAME.cer > $OCSP_PATH/cert/cacert.cer
chmod 444 $OCSP_PATH/cert/cacert.cer

if [ $? -ne 0 ]
then
        exit 1
fi
echo
echo -e "\e[32m < ------------------- IMPORTANT NOTE ----------------------- >"
echo -e "Don't forget to export these environment variables."
echo -e "export OCSP_NAME="$OCSP_NAME
echo -e "export CA_PATH="$OCSP_PATH
echo
echo -e "or execute 'source $CA_PATH/setenv.sh'"
echo -e 'export OCSP_NAME='$OCSP_NAME >> $CA_PATH/setenv.sh
echo -e 'export CA_PATH='$OCSP_PATH >> $CA_PATH/setenv.sh
echo -e 'export PATH='$PATH:$CA_PATH/bin >> $CA_PATH/setenv.sh
echo -e " < ------------------- IMPORTANT NOTE ----------------------- > \e[0m"
echo
echo "OCSP : ["$OCSP_NAME"] setup successfully."
chmod 700 $CA_PATH/setenv.sh
cp $OCSP_PATH/cert/$OCSP_NAME.cer $CA_PATH/web/cert
chmod 444 $CA_PATH/web/cert/$OCSP_NAME.cer
