#!/usr/bin/env bash
clear
current_path=`pwd`
script_path=`dirname $0`
echo
echo "- This script automates the creation of OpenSSL based Online Certificate Status Protocol (OCSP)."
echo "- You're only required to input some information during setup."
echo "- This script assumes that you've already setup a Root CA."
echo
echo -n "Enter OCSP Server name : "
read OCSP_NAME

OCSP_PATH=$HOME/CA
CA_PATH=$OCSP_PATH/$OCSP_NAME

mkdir -p $CA_PATH/{private,cert,issued_certs,crl,csr,data}
chmod 700 $CA_PATH
chmod 700 $CA_PATH/private
openssl rand -hex -out $CA_PATH/private/.rand 16
chmod 600 $CA_PATH/private/.rand
touch $CA_PATH/data/index.dat
openssl rand -hex -out $CA_PATH/data/serial.dat 8
chmod 600 $CA_PATH/data/*
echo "1000" > $CA_PATH/data/crl_number
echo "directories and files for "$OCSP_NAME" setup successfully.".
echo "---------------------------------------------------------------------"
echo 

WEB_URL=`hostname`

cp $script_path/templateissuing $CA_PATH
ISSUING_CNF=$CA_PATH/$OCSP_NAME
mv $CA_PATH/templateissuing $ISSUING_CNF.cnf
echo "Preparing configuration file for "$OCSP_NAME"."
echo -n "Country (C)		: " 
read ISSUING_C
echo -n "State (ST)		: " 
read ISSUING_ST
echo -n "Location (L)		: " 
read ISSUING_L
echo -n "Organization (O)	: " 
read ISSUING_O
echo -n "Org. Unit (OU)		: " 
read ISSUING_OU

sed -i 's@ISSUING_HOME@'"$CA_PATH"'@' $ISSUING_CNF.cnf
sed -i 's@ISSUING_NAME@'"$OCSP_NAME"'@' $ISSUING_CNF.cnf
sed -i 's@COUNTRY@'"$ISSUING_C"'@' $ISSUING_CNF.cnf
sed -i 's@STATE@'"$ISSUING_ST"'@' $ISSUING_CNF.cnf
sed -i 's@LOCATION@'"$ISSUING_L"'@' $ISSUING_CNF.cnf
sed -i 's@ORGANIZATION@'"$ISSUING_O"'@' $ISSUING_CNF.cnf
sed -i 's@ORG_UNIT@'"$ISSUING_OU"'@' $ISSUING_CNF.cnf
sed -i 's@ISSUING_NAME@'"$OCSP_NAME"'@' $ISSUING_CNF.cnf
sed -i 's@WEBLINK@'"$WEB_URL"'@' $ISSUING_CNF.cnf

echo "Configuration file for "$OCSP_NAME" ready."
echo "---------------------------------------------------------------------"
echo 
echo "Select key type."
echo "(1) for RSA. (default)"
echo "(2) for ECDSA."
echo -n "Key Type : "
read KEY_TYPE

if [ -z "$KEY_TYPE" ]
then
	KEY_TYPE=1
fi

if [ $KEY_TYPE -eq 1 ]
then
	echo -n "Key size (default 2048) : "
	read RSA_KEY_SIZE
	if [ -z "$RSA_KEY_SIZE" ] || [ "$RSA_KEY_SIZE" -lt 2048 ]
	then
		RSA_KEY_SIZE=2048
	fi
	openssl genpkey -algorithm rsa -pkeyopt rsa_keygen_bits:$RSA_KEY_SIZE -quiet | openssl pkcs8 -passout file:/etc/machine-id -topk8 -out $CA_PATH/private/$OCSP_NAME.key
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	chmod 400 $CA_PATH/private/$OCSP_NAME.key
fi

if [ $KEY_TYPE -eq 2 ]
then
	echo -n "ECDSA Curve (default secp384r1) : "
	read EC_CURVE
	if [ -z "$EC_CURVE" ]
	then
		EC_CURVE="secp384r1"
	fi
	openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:$EC_CURVE | openssl pkcs8 -passout file:/etc/machine-id -topk8 -out $CA_PATH/private/$OCSP_NAME.key
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	chmod 400 $CA_PATH/private/$OCSP_NAME.key
fi
echo "Private key for $OCSP_NAME generated successfully."
echo "---------------------------------------------------------------------"
echo
echo -n "Certificate validity (days, default 1825) : "
read VALIDITY_DAYS

if [ -z "$VALIDITY_DAYS" ]
then
	VALIDITY_DAYS=1825
fi

if [[ -z "${ROOT_CA_NAME}" ]]
then
	echo -n "Root CA name : "
	read ROOT_CA_NAME
fi
if [[ -z "${ROOT_CA_PATH}" ]]
then
	echo -n "Root CA Path : "
	read ROOT_CA_PATH
fi

if [ $ROOT_CA_PATH == "." ]
then
        ROOT_CA_PATH=$PWD/$ROOT_CA_NAME
fi

ROOT_CNF=$ROOT_CA_PATH/$ROOT_CA_NAME.cnf
sed -i 's@ISSUING_NAME@'"$OCSP_NAME"'@' $ROOT_CNF
sed -i 's@ROOT_NAME@'"$ROOT_CA_NAME"'@' $ISSUING_CNF.cnf
openssl req -config $ROOT_CNF -new -sha256 -key $CA_PATH/private/$OCSP_NAME.key -passin file:/etc/machine-id -out $CA_PATH/csr/$OCSP_NAME.csr
if [ $? -ne 0 ]
then
	exit 1
fi

openssl ca -config $ROOT_CNF -batch -passin file:/etc/machine-id -extensions intermediate_ca -days $VALIDITY_DAYS -notext -md sha256 -in $CA_PATH/csr/$OCSP_NAME.csr -out $CA_PATH/cert/$OCSP_NAME.cer
if [ $? -ne 0 ]
then
        exit 1
fi

chmod 444 $CA_PATH/cert/$OCSP_NAME.cer
openssl verify -CAfile $ROOT_CA_PATH/cert/$ROOT_CA_NAME.cer $CA_PATH/cert/$OCSP_NAME.cer
cat $CA_PATH/cert/$OCSP_NAME.cer $ROOT_CA_PATH/cert/$ROOT_CA_NAME.cer > $CA_PATH/cert/cacert.cer
chmod 444 $CA_PATH/cert/cacert.cer
openssl ca -config $ISSUING_CNF.cnf -gencrl -passin file:/etc/machine-id -out $CA_PATH/crl/$OCSP_NAME.crl
if [ $? -ne 0 ]
then
        exit 1
fi
echo
echo "-----------------------------------------------------------"
echo "Don't forget to export these environment variables."
echo "export OCSP_NAME="$OCSP_NAME
echo "export OCSP_PATH="$CA_PATH
echo
echo "or execute 'source $OCSP_PATH/setenv.sh'"
echo 'export OCSP_NAME='$OCSP_NAME >> $OCSP_PATH/setenv.sh
echo 'export OCSP_PATH='$CA_PATH >> $OCSP_PATH/setenv.sh
echo 'export PATH='$PATH:$OCSP_PATH/bin >> $OCSP_PATH/setenv.sh
echo "-----------------------------------------------------------"
echo
echo "ISSUING CA : ["$OCSP_NAME"] setup successfully."
chmod 700 $OCSP_PATH/setenv.sh
mkdir $OCSP_PATH/bin
cp $script_path/bin/* $OCSP_PATH/bin
cp $CA_PATH/cert/$OCSP_NAME.cer $OCSP_PATH/web/cert
chmod 444 $OCSP_PATH/web/cert/$OCSP_NAME.cer
cp $CA_PATH/crl/$OCSP_NAME.crl $OCSP_PATH/web/crl
chmod 444 $OCSP_PATH/web/crl/$OCSP_NAME.crl
chmod 500 $OCSP_PATH/bin/*
